import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Digital Smart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-full min-h-screen flex justify-center items-center bg-white">
          <div
            className="w-[430px] h-screen bg-cover bg-center flex flex-col justify-between items-center text-white relative"
            style={{ backgroundImage: "url('/bgimg.png')" }} // place fire-ballon image inside /public
          >
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
